version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  lint-and-test:
    executor:
      name: node/default
      tag: "22.13.1"
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run:
          name: Run tests
          command: npm test -- --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test-results
      - store_test_results:
          path: ./test-results

workflows:
  lint-and-test:
    jobs:
      - lint-and-test
